### ISSUE TITLE
sp-build-tasks version update

### ISSUE THREAD

**Issue by koltyakov** [Zerg00s/customHome#1]
Hey Denis,

A new release of sp-build-tasks was published (v 1.4.x).
In the new versions, `./src/scripts` watch approach was changed:
- Previously, gulp-watch detected changes and triggered `gulp:webpack` task
- Now, on first change, gulp-watch triggers once `gulp:webpack-watch`, then changes in .ts(x)/.js(x) are manadeged with webpack with following advantages:
  - Incremental second build (sometimes 3-5 times faster)
  - If multiple outputs are configured, build processes care only for changed trees

**Comment by Zerg00s** [comment]
Fantastic. This is a great change.
